import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, Download, FileText } from 'lucide-react';

export default function DocumentModal({ isOpen, onClose, document, onDownload }) {
  if (!document) return null;

  let parsedData = null;
  try {
    parsedData = document.extracted_data ? JSON.parse(document.extracted_data) : null;
  } catch (e) {
    parsedData = { rawText: document.extracted_data };
  }

  return (
    <AnimatePresence>
      {isOpen && (
        <>
          <motion.div 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            style={{ position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, background: 'rgba(0,0,0,0.7)', zIndex: 1000, backdropFilter: 'blur(4px)' }}
          />
          <motion.div 
            className="card"
            initial={{ opacity: 0, scale: 0.95, y: 20, x: "-50%" }}
            animate={{ opacity: 1, scale: 1, y: 0, x: "-50%" }}
            exit={{ opacity: 0, scale: 0.95, y: 20, x: "-50%" }}
            style={{ 
              position: 'fixed', top: '10vh', left: '50%', 
              width: '90%', maxWidth: '800px', maxHeight: '80vh', overflowY: 'auto', zIndex: 1001,
              border: '1px solid var(--accent-primary)', boxShadow: '0 10px 40px rgba(0,0,0,0.5)'
            }}
          >
            <div className="flex-between mb-6" style={{ borderBottom: '1px solid var(--border-color)', paddingBottom: '1rem' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
                <FileText size={24} className="text-accent-primary" />
                <div>
                  <h3 className="text-2xl">{document.reference_number || document.id}</h3>
                  <p className="text-muted text-sm mt-1">Status: <span className="text-accent-secondary">{document.status}</span></p>
                </div>
              </div>
              <button onClick={onClose} style={{ background: 'transparent', border: 'none', color: 'var(--text-muted)', cursor: 'pointer' }}>
                <X size={24} />
              </button>
            </div>

            <div className="mb-6">
              <h4 className="text-lg text-accent-gradient mb-4">Extracted AI Metadata</h4>
              {parsedData ? (
                <div style={{ background: 'rgba(0,0,0,0.3)', padding: '1rem', borderRadius: '0.5rem', border: '1px solid var(--border-color)', overflowX: 'auto' }}>
                  <pre style={{ margin: 0, color: 'var(--text-main)', fontSize: '0.9rem', lineHeight: '1.5' }}>
                    {JSON.stringify(parsedData, null, 2)}
                  </pre>
                </div>
              ) : (
                <p className="text-muted">No structured data found for this document.</p>
              )}
            </div>

            <div className="flex-between">
              <div className="text-muted text-sm">
                Generated By: <span className="text-main">{document.generated_by || 'Unknown'}</span> <br/>
                Confidence: {document.ai_confidence ? `${document.ai_confidence}%` : '--'}
              </div>
              <button 
                onClick={() => onDownload(document)}
                className="badge flex-center" 
                style={{ gap: '0.5rem', background: 'var(--accent-primary)', color: 'white', border: 'none', cursor: 'pointer', padding: '0.75rem 1.5rem' }}
              >
                <Download size={18} /> Export JSON
              </button>
            </div>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  );
}
